Unbrick core9g25
OrangeTux/orangetux.nl pull request #3
Opened 2018-05-23 18:12 UTC by OrangeTux

2018-05-23 19:01 UTC, Wisse1996 commented on content/post/debrick-core9g25-intro.md
> +that)? Well, you're devices bricked.
you're devices bricked -> your device is bricked, or your devices are bricked.

2018-05-23 19:06 UTC, wipsel reviewed
lekker kort maar krachtig, goeie post wel! zinsbouw dingen even checken verder zeg ik lgtm

2018-05-23 19:06 UTC, Wisse1996 commented on content/post/debrick-core9g25-intro.md
> +Only recently together my college Marten van Houten and I managed to reflash
deze zin loopt niet echt, together weghalen maybe?

2018-05-23 19:06 UTC, Wisse1996 commented on content/post/debrick-core9g25-intro.md
> +the NAND using tools provided but the vendor of the CPU.
but -> by ?

2018-05-23 19:06 UTC, Wisse1996 commented on content/post/debrick-core9g25-intro.md
> +In order to understand fully how we managed to do that I'll explain the boot
understand fully -> fully understand

2018-05-23 19:42 UTC, Appeltabak requested changes
A nicely written blog post! My review consists of a bunch of typo's that needs to be fixed + comments on the structure of some sentences

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +9G25][core9g25]. This System on a Module (SoM) has a the 400 MHz ARM CPU
`has a the` -> `has a`

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +[AT91SAM9G25][at91sam9g25] from Atmel (which has been bought by Microchip). It
`which has been bought by Microchip`. What's the relevance of naming this fact? If this has been done recently, maybe add 'recently', or the specific year / date.  I think this is only interesting when it happened recently or it is not really known.

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +image shows the SoM, it's taken from the website of [CoreWind][corewind].
`SoM, it's taken` -> `SoM, taken`.

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +quite old we reflash the NAND and replace the stack with more recent versions
`reflash` -> `reflashed`
`replace` -> `replaced`

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +of the programs. Reflashing the NAND is dangerous and can lead to bricked and
`bricked and unusable devices`  -> `bricked and therefore unusable devices`. Cause and effect clarified

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +CORE 9G25. In this first post I'll explain how normal reflash procudere and
`how normal` -> `how a normal`
`procudere` -> `procedure`

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +thing, but then Windows is used to fix the NAND.
Make sure you link them here when your wrote the other blog posts

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +Reflashing the content on the Nand is easy when all goes well. During boot, the
Inconsistent capitals

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +bootloader U-boot look for an USB drive to be present. When it's found so
`look` -> `looks`
`U-boot` -> `U-Boot`. Capital B, check the other references too
Remove `so`

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +kernel you've to make sure to put a file called `uImage` on the USB drive.
`you've to` -> `you have to` Maybe it's only when saying out loud, but it seems strange to use the shortened form here :stuck_out_tongue:

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +that)? Well, you're devices bricked.
`you're devices bricked` -> `your devices are bricked` or `You've bricked your devices`

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +Only recently together my college Marten van Houten and I managed to reflash
`Only recently together my` -> `Just recently, my colleague...`

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +the NAND using tools provided but the vendor of the CPU.
`but` -> `by` ?

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +In order to understand fully how we managed to do that I'll explain the boot
understand fully -> fully understand
`how we managed to do that` -> how we managed it` first one is slightly ambiguous

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +NAND flash. But I'll discuss that in 2 other posts.
This post is ended all of a sudden.  It is not that clear when the boot proces has ended. I assume when `The program that is found on `0x0` on the ROM` has been executed? If so, you could add `And that's the boot proces of this AT91SAM9G25 CPU`

For the last paragraph, remove the first sentence and start with `This ROM (64kB) contains..` `... and this program allows one...` (one sentence).

2018-05-23 19:42 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +The AT91SAM9G25 CPU comes with a 64 kB ROM. This ROM contains a program called
` 64 kB ROM. This ROM` -> `64 kB ROM and contains`

2018-05-23 19:43 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +thing, but then Windows is used to fix the NAND.
` but then Windows is used to fix the NAND` to `but using Windows instead of Linux`

2018-05-23 19:44 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +of the programs. Reflashing the NAND is dangerous and can lead to bricked and
`bricked and thus unusable`. Bricked already means the device is unusable.

2018-05-23 19:45 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +Reflashing the content on the Nand is easy when all goes well. During boot, the
`Nand` to `NAND`

2018-05-23 19:45 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +bootloader U-boot look for an USB drive to be present. When it's found so
`look` to `looks`

2018-05-23 19:46 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +bootloader U-boot look for an USB drive to be present. When it's found so
remove `so`

2018-05-23 19:48 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +U-Boot will look for files with specific names, load them into RAM before writing
`names, load` to `names. It loads those files`

2018-05-23 19:49 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +First U-Boot loads the file `at91sam9x5ek-nandflashboot-uboot-3.5.3.bin`, than
`than` to `then`

2018-05-23 19:49 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +writes the file to Nand, aligning the program at address `0x0`.
`Nand` to `NAND`

2018-05-23 19:52 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +Only recently together my college Marten van Houten and I managed to reflash
`Recently my colleague and I managed to reflash the NAND`. This sounds better to me.

2018-05-23 19:57 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +that is when the BMS pin is `0`, the NAND is layed out to this address. So
remove `that is`?

2018-05-23 19:57 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +that is when the BMS pin is `0`, the NAND is layed out to this address. So
`layed` to `laid`

2018-05-23 19:57 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +And which program is at this address? Well, that is AT91Bootstrap.
`which` to `what`

2018-05-23 19:57 UTC, kevba commented on content/post/debrick-core9g25-intro.md
> +Instead of the NAND, the ROM is now layed out at address `0x0`. The program
`layed` to `laid`

2018-05-23 20:33 UTC, OrangeTux commented on content/post/debrick-core9g25-intro.md
> +[AT91SAM9G25][at91sam9g25] from Atmel (which has been bought by Microchip). It
Agree. The point is that all websites with documentation are from Microchip, but the original datasheets contain the Atmel style and logo. I clarified it.

2018-05-24 06:12 UTC, Appeltabak approved these changes
One typo was introduced when fixing another :p

2018-05-24 06:12 UTC, Appeltabak commented on content/post/debrick-core9g25-intro.md
> +quite old we reflashed the NAND and ieplaced the stack with more recent
'ieplaced' - > 'replaced'

2018-05-31 19:17 UTC, closed without merging